const fakeDB = [
    {
        id: 1,
        type: "Explore?",
        title: "Quaking Mat",
        image: "https://picsum.photos/150/75",
        rulesText1: "Test Agility. Failure Restrained. Critical Falure Suffocate",
        rulesText2: "Loot 1000 gold amulet",
        rulesText3: "",
        rulesText4: "",
        flavorText1: "",
        flavorText2: "",
        flavorText3: "",
        flavorText4: "",
    },
    {
        id: 2,
        type: "Wandering Monster!",
        title: "Prowling Wolf Pack",
        image: "https://picsum.photos/150/75",
        rulesText1: "Escape? Test Agility.",
        rulesText2: "1d6 Wolves",
        rulesText3: "10 gold per pelt",
        rulesText4: "",
        flavorText1: "",
        flavorText2: "",
        flavorText3: "",
        flavorText4: "",
    },
    {
        id: 3,
        type: "Event!",
        title: "Gust of Wind",
        image: "https://picsum.photos/150/75",
        rulesText1: "Stamina",
        rulesText2: "Extinguishes Torches and Disappates Fog",
        rulesText3: "",
        rulesText4: "",
        flavorText1: "",
        flavorText2: "",
        flavorText3: "",
        flavorText4: "",
    },
    {
        id: 4,
        type: "Quest!",
        title: "Moonflower Poultice",
        image: "https://picsum.photos/150/75",
        rulesText1: "Monastery Quest",
        rulesText2: "Return poultice to the Monastery",
        rulesText3: "Reward: 2000 Gold",
        rulesText4: "",
        flavorText1: "",
        flavorText2: "",
        flavorText3: "",
        flavorText4: "",
    },
]

export default fakeDB;